### ISSUE TITLE
Error: Excepted condition but got [object Object]

### ISSUE THREAD

**Issue by pixcai** [cypress-io/cypress-webpack-preprocessor#10]
- Operating System: macOS 10.12.1
- Cypress Version: 1.4.1
- Browser Version: N/A

### Is this a Feature or Bug?
A bug

### Current behavior:
Custom webpack config in plugins/index.js:
```js
Error: Excepted condition but got [object Object] in {
  "test": {},
  "include": "undefined",
  "exclude": [
    {}
  ]
}
```

### Desired behavior:
No error

### How to reproduce:
Set up the following plugin file:
```js
const webpack = require('@cypress/webpack-preprocessor')
 
module.exports = (on, config) => {
   // `on` is used to hook into various events Cypress emits
   // `config` is the resolved Cypress config
   const options = webpack.defaultOptions
   const rule = options.webpackOptions.module.rules[0]

   rule.use[0].options.presets.push('babel-preset-stage-0')
   on('file:preprocessor', webpack(options))
}
```

**Comment by chrisbreiding** [comment]
Thanks for the bug report! Looks like the method we were using to clone the default options wiped out the regular expressions, which thoroughly confused webpack. This is now fixed in version [1.1.3](https://github.com/cypress-io/cypress-webpack-preprocessor/releases/tag/v1.1.3).
