### ISSUE TITLE
update lodash to v4.17.20

### ISSUE THREAD

**Issue by SigurdMW** [cypress-io/cypress-webpack-preprocessor#104]
- Operating System: All
- Cypress Version: @cypress/webpack-preprocessor@5.4.4
- Browser Version: n/a

### Is this a Feature or Bug?
Bug, lodash 4.17.19 is vulnerable to Prototype pollution according to snyk: https://app.snyk.io/vuln/SNYK-JS-LODASH-590103

### Desired behavior:
Update package to lodash 4.17.20

**Comment by jennifer-shehane** [comment]
PR: https://github.com/cypress-io/cypress-webpack-preprocessor/pull/105

**Comment by jennifer-shehane** [comment]
@berickson1 PR here https://github.com/cypress-io/cypress-webpack-preprocessor/pull/107
