### ISSUE TITLE
Support async webpack config

### ISSUE THREAD

**Issue by egoist** [cypress-io/cypress-webpack-preprocessor#11]
- Operating System: N/A
- Cypress Version: N/A
- Browser Version: N/A

### Is this a Feature or Bug?

Feature (or a bug since this is supported by webpack since v2)

### Current behavior:

You can't export a `Promise` which resolves to a webpack config object in `webpack.config.js`

### Desired behavior:

https://webpack.js.org/configuration/configuration-types/#exporting-a-promise

### How to reproduce:

Export a Promise.

**Comment by chrisbreiding** [comment]
You can return a promise from the plugins file function, which allows you to wait for the promise to resolve before hooking into the 'file:preprocessor' event:

```
const webpack = require('@cypress/webpack-preprocessor')
const getConfig = require('../../webpack.config')

module.exports = (on) => {
  return getConfig().then((webpackConfig) => {
    on('file:preprocessor', webpack(webpackConfig))
  })
}
```
