### ISSUE TITLE
Crash with the error: `Multiple assets emit to the same filename`

### ISSUE THREAD

**Issue by floriansimon1** [cypress-io/cypress-webpack-preprocessor#12]
- Operating System: Debian Stretch
- Cypress Version: 1.4.1
- Browser Version: none

### Is this a Feature or Bug?
Bug

### Current behavior:
When I load my Webpack config as mentioned in this project's README, Webpack gives the following:

```
chunk manifest [entry]
open-app-cypress.js
Conflict: Multiple assets emit to the same filename open-app-cypress.js
Error: Conflict: Multiple assets emit to the same filename open-app-cypress.js
```

### Desired behavior:
No error should be displayed

### How to reproduce:
Pass in the webpack config passed by a project initialized with `vue-cli` to this plugin.

### Additional Info (images, stack traces, etc)
`open-app-cypress.js` is the name of my sample test file.
It might be related to the fact that test files are processed twice?

**Comment by chrisbreiding** [comment]
I'm having trouble reproducing the issue. Here's a working example of using vue-cli and Cypress: https://github.com/bahmutov/vue-cli-and-cypress, which leads me to believe there's something specific about your configuration that causes the problem.

Could you post the contents of your `webpack.config.js` and `cypress/plugins/index.js`?

**Comment by floriansimon1** [comment]
Apologies for not closing this earlier. This was due to a misconfiguration on my part. I included the whole webpack config instead of only the loaders.
