### ISSUE TITLE
Webpack 4 ts-loader issue

### ISSUE THREAD

**Issue by Anoupz** [cypress-io/cypress-webpack-preprocessor#14]
- Operating System: Mac OS
- Cypress Version: Latest
- Browser Version: Latest

### Current behavior:
I use Cypress with typescript and with library https://github.com/bahmutov/add-typescript-to-cypress. It uses @cypress/webpack-preprocessor and ts-loader to compile spec files written in typescript. After upgrading to webpack 4 and ts-loader 4 [Which doesn't support webpack 3 or webpack 2 ] I get Module build failed: TypeError: Cannot read property 'afterCompile' of undefined. This is due to @cypress/webpack-preprocessor using webpack 3 version as the dependency.

### Desired behavior:
I have a working repo with a fix and running tests (its just one line update of webpack version )but would like to create PR. If you could let me know it would be of great help

**Comment by chrisbreiding** [comment]
Feel free to submit a PR. 

My concern is if upgrading webpack will be a breaking change for users with Webpack 3. The best solution may be to allow users to provide their own webpack so it can work regardless of the version.

**Comment by RomanGotsiy** [comment]
Just updating `webpack` in the dependencies to `webpack@^4.0.0` fixes the issue for me.

> My concern is if upgrading webpack will be a breaking change for users with Webpack 3.

Lots of other loaders have already upgraded webpack. Usually they just make a major release and tell users to use e.g. `3.x` with webpack 3 and `4.x` with webpack 4.
Example from [ts-loader](https://github.com/TypeStrong/ts-loader):

![image](https://user-images.githubusercontent.com/3975738/37556915-71b9c9d8-2a05-11e8-81ee-ddd4c0c86174.png)

**Comment by brian-mann** [comment]
So it seems we just need to release a new breaking version so people can opt into it, and it won't break anyone using `^` in semver right?

**Comment by RomanGotsiy** [comment]
@brian-mann absolutely correct!

**Comment by chrisbreiding** [comment]
Just published [2.0.0](https://www.npmjs.com/package/@cypress/webpack-preprocessor) with webpack 4 support. Users can use 1.x for webpack 2 or 3.

**Comment by RomanGotsiy** [comment]
Nice! I would just put Compatibility section right after Installation in README
