### ISSUE TITLE
Breaks Eslint in Project

### ISSUE THREAD

**Issue by egucciar** [cypress-io/cypress-webpack-preprocessor#18]
- Operating System: MacOS
- Cypress Version: 2.1.0
- Browser Version: N/A

### Is this a Feature or Bug?
Bug

### Current behavior:
Installing this as a dependency breaks ESLinter - Eslinter fails to recognize experimental values

Eslint deps:
`babel-eslint: ^7.2.3`
`eslint: ^3.19.9`
`eslint-plugin-cypress: ^2.0.1`

My eslint config:
```
module.exports = {
  plugins: ['cypress'],
  env: {
    browser: true,
    es6: true,
    node: true,

    'cypress/globals': true,
  },
  extends: 'eslint:recommended',
  parser: 'babel-eslint',
  parserOptions: {
    sourceType: 'module',
  },
  rules: {
    indent: ['error', 2, { SwitchCase: 1 }],
    'linebreak-style': ['error', 'unix'],
    quotes: [
      'error',
      'single',
      { allowTemplateLiterals: true, avoidEscape: true },
    ],
    semi: ['error', 'always'],
    'one-var': [2, 'never'],
    'no-unused-vars': [2, { args: 'none' }],
  },
};
```

### Desired behavior:
I should be able to use the preprocessor without it interfering with my Eslint options.

### How to reproduce:
It should theoretically be reproducable with my eslint options and using experimental class features

https://github.com/babel/babel-eslint/issues/487

Note the static and stuff. This results in false negatives when i have this preprocessor installed, but not when i do not. Very frustrating!

**Comment by chrisbreiding** [comment]
Which version of this preprocessor are you using? 

This looks to be an issue with `babel-eslint`, and based on that issue, some people were able to fix it by upgrading it. Have you had any luck upgrading `babel-eslint`?

**Comment by egucciar** [comment]
Updating babel-eslint was not an option as newer versions of that would break other things. I have reworked the project to not require the webpack preprocessor so that I could be unblocked.

**Comment by chrisbreiding** [comment]
Okay. I'm going to close this as it seems to primarily be an issue with `babel-eslint`.
