### ISSUE TITLE
Outdated Dependencies

### ISSUE THREAD

**Issue by ethikz** [cypress-io/cypress-webpack-preprocessor#23]
- Operating System: OSX 10.12
- Cypress Version: 3.0.3
- Browser Version: 68.0.3440.106

### Is this a Feature or Bug?
Bug

### Current behavior:
Using the newer babel, `@babel/core: 7.0.0`, cypress webpack-preprocessor doesn't work.  It returns an error about dependencies needing to be updated.

```
./cypress/integration/notifications.js
Module build failed (from ./node_modules/@cypress/webpack-preprocessor/node_modules/babel-loader/lib/index.js):
Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.0". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.
```

Looks like this is being fixed in #22

**Comment by chrisbreiding** [comment]
Babel 7 support was added in [v3.0.0](https://github.com/cypress-io/cypress-webpack-preprocessor/releases/tag/v3.0.0).
