### ISSUE TITLE
You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by HamedFathi** [cypress-io/cypress-webpack-preprocessor#27]
- Operating System: Win 7 / 10
- Cypress Version: latest
- Browser Version: latest

### Is this a Feature or Bug?
Bug

### Current behavior:
![image](https://user-images.githubusercontent.com/8418700/46569001-46b0d100-c95b-11e8-8ffa-8e49367a2652.png)

### Desired behavior:

load any `.ts` files without a problem.

### How to reproduce:
This is very simple `ts` file for getting Google title based on a `ts` class field.

### Additional Info (images, stack traces, etc)

This is my code
```ts
/// <reference types="cypress" />
import expect from "expect";
describe('My First Test', function () {
  it('get Google site title"', function () {
    cy.visit('https://www.google.com/');

    cy.title().should('eq', new Test().message)
  })
})

export class Test {
  message = "Google"; /* (23:10)  */
}
```

**Comment by FredyC** [comment]
I had the same problem and this is what I did to fix it. Note I am using Babel support for TypeScript.

<details>
  <summary>cypress/package.json</summary>

```json
{
  "dependencies": {
    "@babel/core": "^7.4.4",
    "@babel/preset-env": "^7.4.4",
    "@babel/preset-typescript": "^7.3.3",
    "@types/node": "^11.13.8",
    "@cypress/webpack-preprocessor": "^4.0.3",
    "babel-loader": "^8.0.5",
    "cypress": "^3.2.0",
    "typescript": "^3.4.5"
  },
  "scripts": {
    "start": "cypress open"
  }
}

```
</details>


<details>
  <summary>cypress/webpack.config.js</summary><p>

```js
module.exports = {
  resolve: {
    extensions: ['.ts'],
  },
  module: {
    rules: [
      {
        test: /\.ts$/,
        exclude: [/node_modules/],
        use: [
          {
            loader: 'babel-loader',
            options: {
              presets: ['@babel/preset-env', '@babel/preset-typescript'],
            },
          },
        ],
      },
    ],
  },
}
```

</p>
</details>

<details>
  <summary>cypress/plugins/index.js</summary>

```js
const webpack = require('@cypress/webpack-preprocessor')
module.exports = on => {
    on('file:preprocessor', webpack())
}
```
</details>

<details>
  <summary>cypress/tsconfig.json</summary>

```json
{
  "compilerOptions": {
    "strict": true,
    "baseUrl": "../node_modules",
    "target": "es5",
    "lib": ["es5", "dom"],
    "types": ["cypress"]
  },
  "include": ["**/*.ts"]
}
```
</details>

**Comment by Bkucera** [comment]
closing as this doesn't look like an issue with the preprocessor
