### ISSUE TITLE
Consider disable optimization so debugger statements are not stripped

### ISSUE THREAD

**Issue by Strajk** [cypress-io/cypress-webpack-preprocessor#29]
- Cypress Version: 3.1.0
- Package Version: 3.0.0

### Is this a Feature or Bug?

Not expected behavior

### Current behavior:

`debugger` statements are stripped from tests with default settings of `cypress-webpack-preprocessor`

### Desired behavior:

Should not be stipped or at least it should be very well documented

### How to reproduce:

```
Cypress.on("fail", (err, runnable) => {
  console.log("I'm here!!!")
  debugger // eslint-disable-line no-debugger
  return err
})
```

is compiled to

```
Cypress.on("fail", function(e, t) {
  return console.log("I'm here!!!"),
  e
}),
```

adding 

```
const options = webpack.defaultOptions
  options.webpackOptions.optimization = { minimize: false } // THIS!
  on("file:preprocessor", webpack(options))
```

will not strip the `debugger`

---

I can submit PR if you will agree

**Comment by chrisbreiding** [comment]
Wow, that's annoying webpack does that by default. A PR would be more than welcome.

**Comment by brian-mann** [comment]
Closed by https://github.com/cypress-io/cypress-webpack-preprocessor/pull/87
