### ISSUE TITLE
Webpack silently fails when user config defined code split chunks

### ISSUE THREAD

**Issue by LinusBorg** [cypress-io/cypress-webpack-preprocessor#31]
- Operating System: Windows 7 / Mac OS X Sierra
- Cypress Version: 3.1.0
- Browser Version: FF 62

### Is this a Feature or Bug?

Bug

### Current behavior:

When the user provides a webpack configuration that includes any sort of code splitting, i.e. with the [`optimization.splitChunks`](https://webpack.js.org/plugins/split-chunks-plugin/) option, compilation silently fails and cypress says that the test file doesn't contain any tests.

### Desired behavior:

The preprocessor should correctly transpile test files and tests should be run.

### How to reproduce:

Will prodive repo asap.

### Additional Info (images, stack traces, etc)

Related issues: 

* https://github.com/cypress-io/cypress/issues/2564
* https://github.com/vuejs/vue-cli/issues/2745

As far as I understand the source of this preprocessor plugin, the problem is that it's designed to work with exactly one bundle file.

A possible solution would be to make sure that any user-provided webpack config doesn't contain any code splitting config:

https://github.com/cypress-io/cypress-webpack-preprocessor/blob/master/index.js#L64-L65

#### before
```javascript
// user can override the default options
let webpackOptions = Object.assign({}, defaultOptions.webpackOptions, options.webpackOptions)
```

#### after
```javascript
// user can override the default options
const userWebpackOptions = options.webpackOptions
if (userWebpackOptions.optimization) {
  userWebpackOptions.runtimeChunk = undefined
  userWebpackOptions.splitChunks = undefined
}
let webpackOptions = Object.assign({}, defaultOptions.webpackOptions, options.webpackOptions)
```

#### Other possible solutions

Maybe another solution would be to provide info about all generated chunks to cypress so it can serve them all? That's not something I can judge though.
Maybe it

**Comment by drewbrend** [comment]
Thank you for opening this issue.  I was ripping my hair out over this for hours and I have no idea how I would have figured this out if I didn't stumble on this issue.

Mine was failing silently while compiling the `/support/` files, my specs were okay.  So I was still able to run the tests and was presented with no errors in the terminal or chrome console, but my custom commands were all missing!

I removed the optimization section from the webpack config and everything worked fine.

An error output in this scenario would be a huge time saver for the next poor sucker that hits this issue.

**Comment by Pharserror** [comment]
Not really sure where this should go but, I wanted to get this out there.
I was having a similar issue where Cypress was complaining about:
```
chunk runtime [entry]
index.spec.js
Conflict: Multiple assets emit to the same filename index.spec.js
Error: Conflict: Multiple assets emit to the same filename index.spec.js
```
I figured the culprit was `webpack.optimization.CommonsChunkPlugin` in my config. This is my workaround in Cypress/plugins/index.js:
```javascript
const webpack = require('@cypress/webpack-preprocessor');
const webpackOptions = require('../../webpack.base.config.js');

webpackOptions.plugins = webpackOptions.plugins.reduce(
  (plugins, plugin) => {
    if (plugin.constructor.name !== 'CommonsChunkPlugin') {
      plugins.push(plugin);
    }

    return plugins;
  },
  []
);

module.exports = (on, config) => {
  on('file:preprocessor', webpack({ watchOptions: {}, webpackOptions }));
};
```
So far, it seems to have fixed the issue: I'm now getting messages about the actual tests themselves - which leads me to believe they are actually running.

**Comment by bahmutov** [comment]
In `cypress-react-unit-test` we clean the loaded webpack file https://github.com/bahmutov/cypress-react-unit-test/blob/feature/cypress-mount-mode/plugins/load-webpack/index.js see the logic in https://github.com/bahmutov/find-webpack/blob/master/src/clean-for-cypress.js#L62

You could do the same in your plugins code
