### ISSUE TITLE
SyntaxError: 'import' and 'export' may appear only with 'sourceType: module'

### ISSUE THREAD

**Issue by ludmilanesvitiy** [cypress-io/cypress-webpack-preprocessor#41]
- Operating System: Linux
- Cypress Version: latest
- Browser Version: latest

### Is this a Feature or Bug?
BUG/Question

### Current behavior:
I'm trying to create e2e tests with Cypress + Cucumber + Typescript + cypress/webpack-preprocessor
When step-definition file don't have imports/exports - everything works well
But when I'm trying to use PageObjects in TS, using export-import statement, then I got an error like  'import' and 'export' may appear only with 'sourceType: module'

I don't have the possibility to change imports and exports to require and module.export because in my current project I have a lot of PO's and I want to save 2 approaches in tests: default approach and BDD approach
### Desired behavior:
Possibilities to use import and export

### How to reproduce:
https://github.com/ludmilanesvitiy/cypress-cucumber-example/pull/1/files
In this PR you can see how to reproduce the issue
In the main repository all works well.

**Comment by chrisbreiding** [comment]
It looks like you're using [cypress-cucumber-preprocessor](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor) to handle `.ts` files, so the issue is with that package and not with this one.

**Comment by ludmilanesvitiy** [comment]
@chrisbreiding I've created similar issue there: https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/112 , but I want to mention that I'm using both preprocessors: 
const cucumber = require('cypress-cucumber-preprocessor').default;
const webpack = require('@cypress/webpack-preprocessor');
If my tests written with bdd approach, only then I'm using cucumber. In other cases - webpack. If you can advise anything for making this compatible to each other - I'll really appreciate it.

**Comment by stephanmullerNL** [comment]
@ludmilanesvitiy I'm running into the exact same issue, have you found a solution yet?

**Comment by ludmilanesvitiy** [comment]
@stephanmullerNL Have only 1 solution - don't use page object pattern or similar approach. But this issue still exists, I've added commit for quick replication, see https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/112#issuecomment-458175012
