### ISSUE TITLE
Transpiling spread syntax, cannot find module

### ISSUE THREAD

**Issue by Tjark-Kuehl** [cypress-io/cypress-webpack-preprocessor#42]
- Operating System: Ubuntu 18.10
- Cypress Version: 3.1.3
- Browser Version: Electron 59 (headless)

### Is this a Feature or Bug?
Bug

### Current behavior:
It doesn't transpile at all.
Tried preset-es2015 and preset-env but none of them work.
Would appreciate an example.

Here is what I did
`
    const options = webpack.defaultOptions
    options.webpackOptions.module.rules[0].use[0].options.presets.push(
        '@babel/preset-es2015'
    )
    on('file:preprocessor', webpack(options))
`

### Desired behavior:
It transpiles and runs in headless mode without crashing

### How to reproduce:
Try out my config with simple object spread operators

### Additional Info (images, stack traces, etc)

./tests/e2e/support/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module '@babel/preset-es2015' from '/home/tjark/git/exomia-cloud/vue'

This occurred while Cypress was compiling and bundling your test code. This is usually caused by:

- A missing file or dependency
- A syntax error in the file or one of its dependencies

Fix the error in your code and re-run your tests.

**Comment by chrisbreiding** [comment]
Object spread is still in the proposal stage, so you need a special babel plugin for it: [@babel/plugin-proposal-object-rest-spread](https://www.npmjs.com/package/@babel/plugin-proposal-object-rest-spread).
