### ISSUE TITLE
No progress feedback while preprocessor is running

### ISSUE THREAD

**Issue by zakhenry** [cypress-io/cypress-webpack-preprocessor#46]
- Operating System: MacOS, Ubuntu
- Cypress Version: 3.1.5
- Browser Version: Chrome 72

### Is this a Feature or Bug?
Feature

### Current behavior:
When preprocessor is running, cypress window boots and shows a blank output while preprocessor is running. If you have a slow compilation process e.g. typescript, it can be confusing waiting for ~20 seconds while nothing appears to happen

### Desired behavior:
Indication of the progress of the plugin, or even just a notice that the preprocessor is running, standby...

### How to reproduce:
Use the preprocessor plugin, make it wait for an extended period of time

**Comment by chrisbreiding** [comment]
I recommend re-submitting this in the [main cypress repo](https://github.com/cypress-io/cypress/issues), because that's where the work would have to be done to show the progress in the UI and it would be independent of which preprocessor you use.

**Comment by zakhenry** [comment]
Moved to https://github.com/cypress-io/cypress/issues/4393
