### ISSUE TITLE
Empty plugins file error

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-webpack-preprocessor#5]
If the plugins file is empty, the error message is weird

<img width="1094" alt="screen shot 2017-10-17 at 2 12 16 pm" src="https://user-images.githubusercontent.com/2212006/31681463-4c3bae92-b345-11e7-841b-ba17ef46aa53.png">

**Comment by chrisbreiding** [comment]
What's weird about it? It tells you exactly what's wrong.

**Comment by bahmutov** [comment]
`exported [object Object]` is wrong :)

**Comment by chrisbreiding** [comment]
Better?

![screen shot 2017-10-17 at 2 45 10 pm](https://user-images.githubusercontent.com/1157043/31683099-f253c04a-b349-11e7-9207-e5142deab5de.png)

**Comment by bahmutov** [comment]
much better, thank you!
Now let's see how you commit with message and close this issue and post message when new NPM version gets published - all automatically!

**Comment by chrisbreiding** [comment]
Sorry to tell you, this is in the main cypress repo: https://github.com/cypress-io/cypress/commit/e0f13cb28e4b17de4007ec62ea53d4d3659f3af5
