### ISSUE TITLE
Cannot load first config

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-webpack-preprocessor#6]
Plugins file (valid file)
```js
const webpackPreprocessor = require('@cypress/webpack-preprocessor')
module.exports = (register, config) => {
  register('on:spec:file:preprocessor', webpackPreprocessor(config))
}
```
Cypress `preprocessor-refactor` shows error message

<img width="1089" alt="screen shot 2017-10-17 at 2 10 35 pm" src="https://user-images.githubusercontent.com/2212006/31681518-7635c8fe-b345-11e7-9efc-a5767a00b051.png">

**Comment by chrisbreiding** [comment]
Fixed in 1.0.2
