### ISSUE TITLE
Error: Cannot find module 'babel-preset-env'

### ISSUE THREAD

**Issue by westhomas** [cypress-io/cypress-webpack-preprocessor#60]
- Operating System:
macOS 10.15.2 (19C57)
```
$ npm --version
6.10.2
$ node --version
v12.8.1
$ nvm ls
->      v12.8.1
$ nvm --version
0.35.0
```

- Cypress Version:
```
    "@babel/core": "^7.8.4",
    "@babel/preset-env": "^7.8.4",
    "@cypress/webpack-preprocessor": "^4.1.1",
    "babel-loader": "^8.0.6",
    "cypress": "^3.4.1",
    "webpack": "^4.41.5"
```

- Browser Version:
Chrome
Version 79.0.3945.130 (Official Build) (64-bit)

### Is this a Feature or Bug?
Bug

### Current behavior:
Following readme on a brand new cypress install yields exception when looking for module 'babel-preset-env' 

### Desired behavior:
Get a basic webpack options file:preprocessor working.

### How to reproduce:

Cypress@3.4.1
```
git clone https://github.com/westhomas/cypress-playground -b webpack-preprocessor-3.4.1
cd cypress-playground && npm install && npm run test
```

Cypress@4.0.0
```
git clone https://github.com/westhomas/cypress-playground -b webpack-preprocessor-4.0.0
cd cypress-playground && npm install && npm run test
```

### Additional Info (images, stack traces, etc)

```
./cypress/integration/examples/actions.spec.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module 'babel-preset-env' from '/Users/wes/Code/cypress-playground'
 @ multi ./cypress/integration/examples/actions.spec.js main[0]
```

My ultimate goal is to get support for the `@babel/plugin-syntax-dynamic-import` but I can't even get it to work in a basic way first.

**Comment by chrisbreiding** [comment]
Please refer to the following section of the README:

> This package relies on the following peer dependencies:
> 
> - @babel/core
> - @babel/preset-env
> - babel-loader
> - webpack
> 
> It is likely you already have these installed either directly or as a transient dependency, but if not, you will need to install them.
> 
> `npm install --save-dev @babel/core @babel/preset-env babel-loader webpack`

**Comment by westhomas** [comment]
@chrisbreiding I have those installed. I put that in my ticket:

```
    "@babel/core": "^7.8.4",
    "@babel/preset-env": "^7.8.4",
    "@cypress/webpack-preprocessor": "^4.1.1",
    "babel-loader": "^8.0.6",
    "cypress": "^3.4.1",
    "webpack": "^4.41.5"
```

**Comment by westhomas** [comment]
Your README shows a default of `presets: ['babel-preset-env'],` but your code shows a default of `presets: [stubbableRequire.resolve('@babel/preset-env')],` here:

https://github.com/cypress-io/cypress-webpack-preprocessor/blob/master/index.js#L25

Changing my code to `presets: ['@babel/preset-env'],` resolves this issue.

Maybe your README should be updated so as not to lead people down the wrong path?

**Comment by chrisbreiding** [comment]
Sorry for the confusion. We'll fix the README.
