### ISSUE TITLE
Add types

### ISSUE THREAD

**Issue by OliverJAsh** [cypress-io/cypress-webpack-preprocessor#67]
Hey! Could we add these types to the repository so TS users don't have to define them manually? 😄 

```ts
declare module '@cypress/webpack-preprocessor' {
  import * as webpack from 'webpack';

  type FilePreprocessor = (file: Cypress.FileObject) => string | Promise<string>;

  namespace _default {
    export type Options = { webpackOptions: webpack.Configuration };
  }

  const _default: (options: _default.Options) => FilePreprocessor;

  export = _default;
}
```

**Comment by jennifer-shehane** [comment]
This is very low priority for us, but we would be open to a PR.

**Comment by NickBolles** [comment]
@OliverJAsh are you using typescript in plugin files? if so how? Regardless, VSCode uses typescript types for intellisense for javascript too. I'll take a crack at this today.

**Comment by OliverJAsh** [comment]
Yes, via the `checkJs` compiler option.

**Comment by OliverJAsh** [comment]
Does it include types for module `@cypress/webpack-preprocessor`?

**Comment by OliverJAsh** [comment]
E.g. if I do this in my plugins file:

```js
const webpack = require('@cypress/webpack-preprocessor');
```

I want `webpack` to have types.

**Comment by OliverJAsh** [comment]
Unfortunately this is not quite fixed: https://github.com/cypress-io/cypress-webpack-preprocessor/pull/72/files#r404905879

Can we re-open? @chrisbreiding

**Comment by chrisbreiding** [comment]
Properly fixed in [`5.1.1`](https://github.com/cypress-io/cypress-webpack-preprocessor/releases/tag/v5.1.1)

**Comment by OliverJAsh** [comment]
How do I import the `Options` type? I would like to use that type to annotate my options.

**Comment by OliverJAsh** [comment]
```ts
const webpack = require('@cypress/webpack-preprocessor');
// Namespace '_default' has no exported member 'Options'
/** @type {webpack.Options} */
const options = {
  webpackOptions: {}
}
```
