### ISSUE TITLE
Sources maps are not generated for typescript files

### ISSUE THREAD

**Issue by blaugold** [cypress-io/cypress-webpack-preprocessor#68]
- Operating System: Ubuntu
- Cypress Version: 4.1.0
- Browser Version: Chrome 80

### Is this a Feature or Bug?
Bug

### Current behavior:
No source maps are generated for typescript files. 

### Desired behavior:
Source maps should be available for test files.

### How to reproduce:
1. Clone <https://github.com/cypress-io/cypress-example-recipes>
1. run `npm install`
1. run `cd examples/preprocessors__typescript-webpack`
1. uncomment `debugger` in `cypress/integration/spec.ts`
1. run `npx cypress open`
1. open `spec.ts`
1. open devtools
1. rerun tests
1. devtools show transpiled file

### Additional Info (images, stack traces, etc)
It seems that webpack does not generate the source maps when the the extension of the output file is `.ts`. Js files in the same project have source maps generated.

**Comment by jp7677** [comment]
I had the same issue, though after a lot of digging I finally got sourcemaps by adding the `SourceMapDevToolPlugin` plugin to my webpack configuration plus configuring `*.ts` to `options.test` of that plugin. Thus by specifying:

```javascript
plugins: [
  new webpack.SourceMapDevToolPlugin({ test: /\.ts$/ })
]
```
See https://github.com/jp7677/hellocoreclr/blob/master/ui/test-e2e/plugins.js#L19 for a complete example.

I would love to know why this is needed. I don't had to to this with other webpack configurations where I use typescript.

**Comment by jp7677** [comment]
Maybe this comment provides a clue: https://github.com/webpack/webpack/pull/4314#issuecomment-281814922
