### ISSUE TITLE
Silent / wrong error message if the user forgets to install `ts-loader`

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-webpack-preprocessor#8]
I think this is a bug

```
Cypress 1.1.2
@cypress/webpack-preprocessor@1.1.0
```

- start new project
- install Cypress
- install @cypress/webpack-preprocessor
- create `webpack.config.js` file, for example in the root with recommended example options in the typescript webpack example

https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/preprocessors__typescript-webpack/cypress/plugins/index.js

https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/preprocessors__typescript-webpack/webpack.config.js

I like putting `webpack.config.js` right next to the plugins/index.js file

```js
// plugins/index.js
const wp = require('@cypress/webpack-preprocessor')

module.exports = (on) => {
  const options = {
    webpackOptions: require('./webpack.config'),
  }
  on('file:preprocessor', wp(options))
}
```
```js
// webpack.config.js
module.exports = {
  resolve: {
    extensions: ['.ts', '.js'],
  },
  module: {
    rules: [
      {
        test: /\.ts$/,
        exclude: [/node_modules/],
        use: [{
          loader: 'ts-loader',
        }],
      },
    ],
  },
}
```

**note** I forgot to install `ts-loader` as dev dependency.

- start Cypress with debug output `DEBUG=cypress:* $(npm bin)/cypress open`
- click on the `spec.ts` file

<img width="546" alt="screen shot 2017-11-29 at 4 21 27 pm" src="https://user-images.githubusercontent.com/2212006/33402744-8908a502-d52b-11e7-8072-b43a7fd9489c.png">

But the actual problem in the debug log
```
  cypress:server:controllers:spec send /Users/irinakous/Library/Application Support/Cypress/cy/production/projects/test-ts-a2194cba4a58c59bbe6f6fefa72b735c/bundles/cypress/integration/spec.ts +1ms
Error: ENOENT: no such file or directory, stat '/Users/irinakous/Library/Application Support/Cypress/cy/production/projects/test-ts-a2194cba4a58c59bbe6f6fefa72b735c/bundles/cypress/integration/spec.ts'
    at Error (native)

Error: ENOENT: no such file or directory, stat '/Users/irinakous/Library/Application Support/Cypress/cy/production/projects/test-ts-a2194cba4a58c59bbe6f6fefa72b735c/bundles/cypress/integration/spec.ts'
    at Error (native)

GET /__cypress/tests?p=cypress/integration/spec.ts-134 500 63.710 ms - 21
```

We get 500 error trying to bundle spec file using non-installed `ts-loader` module, but we do not communicate this error to the user.

**Comment by chrisbreiding** [comment]
Fixed in `@cypress/webpack-preprocessor@1.1.1`
