### ISSUE TITLE
Remove optimization object

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-webpack-preprocessor#88]
When we bundle specs, we usually cannot use the Webpack optimizations https://webpack.js.org/configuration/optimization/

So we should delete this property from the webpack object if present

**Comment by brian-mann** [comment]
I read through webpacks source code - and by setting the `mode` property to `development`, this effectively takes care of this feature. You cannot set `optimization` to an empty object or `false` - webpack **always** internally sets the optimizations no matter what.

The only way I figure we can override this is to **always** reset `optimization` back to the defaults provided by `mode: 'development'` but I think that is super non-intuitive. For that reason I'm going to close this issue.
