### ISSUE TITLE
webpack sourceMap error in 5.4.0

### ISSUE THREAD

**Issue by obartra** [cypress-io/cypress-webpack-preprocessor#93]
Hi there, thanks for your work on cypress-webpack-preprocessor. It's been working great for us. I was just trying to update to the latest version and ran into some issues. Let me know if I can provide any additional info. 

- Operating System: MacOS 10.15.3
- Cypress Version: 4.5.0
- Browser Version: Google Chrome 81.0.4044.138 (Official Build) (64-bit)

### Is this a Feature or Bug?

I'm guessing a breaking config change between 5.3.0 and 5.4.0 but I couldn't figure out how to make it work.

### Current behavior:

`@cypress/webpack-preprocessor@5.4.0` throws an error when trying to generate source maps

### Desired behavior:

Tests run

### How to reproduce:

This is my webpack config:

```js
const webpack = require('@cypress/webpack-preprocessor');

const extensions = ['.ts', '.tsx', '.js'];
const webpackOptions = {
  resolve: {
    extensions,
  },
  module: {
    rules: [
      {
        test: /\.tsx?$/,
        loader: 'ts-loader',
        options: { transpileOnly: true, sourceMaps: false },
      },
    ],
  },
};

module.exports = (on) => {
  on('file:preprocessor', (file) =>
    webpack({
      webpackOptions,
    })(file)
  );
};
```

Just trying to load any test fails with the webpack error below

### Additional Info (images, stack traces, etc)

<img width="774" alt="error" src="https://user-images.githubusercontent.com/3877773/82244886-cd2ee200-98f6-11ea-9b63-c6de0d72fd0d.png">

**Comment by brian-mann** [comment]
Fixing this now

**Comment by brian-mann** [comment]
This is because you're passing `transpileOnly` option. If you drop that for now it will work... I'll get out a patch for this.

**Comment by josephzidell** [comment]
👍 for fixing this as I'm facing this issue as well

**Comment by obartra** [comment]
It's working well for me, thanks for the fast turnaround! 🎉

**Comment by josephzidell** [comment]
works well. Thanks for the quick fix 🥇
