### ISSUE TITLE
Error: Webpack Compilation Error

### ISSUE THREAD

**Issue by hardikrana437** [cypress-io/cypress-webpack-preprocessor#96]
- Operating System: Windows
- Cypress Version: 3.8.3
- Browser Version: Chrome 83.0.4103.116

### Is this a Feature or Bug? Bug

When I ran cypress run:

It is giving  Webpack compilation error
### Current behavior:
`Webpack Compilation Error
./cypress/integration/features/Pagination.feature
 Module not found: Error: Can't resolve 
'C:UsersCypressProjectode_modulescypress-cucumber-preprocessorlibesolveStepDefinition' in 'C:\Users\CypressProject\cypress\integration\features'`

**I observed \ , \n , \r missing from the path(1st line of error)**

My webpack.config.js file looks like this: 
```js
module.exports = {
resolve: {
  extensions: [".ts", ".js"]
},

node: { fs: "empty", child_process: "empty", readline: "empty" },
module: {
  rules: [
    {
      test: /\.ts$/,
      exclude: [/node_modules/],
      use: [
        {
          loader: "ts-loader"
        }
      ]
    },
    {
      test: /\.feature$/,
      use: [
        {
          loader: "cypress-cucumber-preprocessor/loader"
        }
      ]
    }
  ]
}
};
```

cypress/plugins/index.js
```js

const wp = require('@cypress/webpack-preprocessor')

const fs = require('fs-extra')
const path = require('path')

function getConfigurationByFile (file) {
  const pathToConfigFile = path.resolve('./cypress/', 'config', `${file}.json`)
  return fs.readJson(pathToConfigFile)
}

module.exports = (on,config) => {
    const file = process.env.ENV_FILE//config.env.envFile
  const options = {     
    webpackOptions: require("../webpack.config.js")
  };
  on('file:preprocessor', wp(options))
  if(file==null){
  return getConfigurationByFile('local');
  }
  else{
    return getConfigurationByFile(file);
  }
}

```

**Comment by jennifer-shehane** [comment]
I'm not able to reproduce the error with the information given. During `cypress open`, it opens the feature file. 

I see that you are using an older version of Cypress. Please update to the [current version of Cypress](https://on.cypress.io/changelog) and let us know if this is still happening for you. Your issue may have already been fixed. Thanks!
